### ISSUE TITLE
Server Python crash

### ISSUE THREAD

**Issue by RodMitchell** [nlplab/brat#1133]
Traceback (most recent call last):
The following errors are raised when starting Brat. 
OS=Ubuntu 12.04
Any ideas on how to fix?
File "/var/www/brat/server/src/server.py", line 322, in serve
return _safe_serve(params, client_ip, client_hostname, cookie_data)
File "/var/www/brat/server/src/server.py", line 197, in _safe_serve
json_dic = dispatch(http_args, client_ip, client_hostname)
File "/var/www/brat/server/src/dispatch.py", line 308, in dispatch
json_dic = action_function(*action_args)
File "/var/www/brat/server/src/document.py", line 497, in get_directory_information
base_names = [fn[0:-4] for fn in _listdir(real_dir)
File "/var/www/brat/server/src/document.py", line 416, in _listdir
and allowed_to_read(path_join(directory, f))]
File "/usr/lib/python2.7/posixpath.py", line 69, in join
path += b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Previous document (Cursor Left)Next document (Cursor Right)

**Comment by RodMitchell** [comment]
Resolved. A folder name in data had a non-English character.
