### ISSUE TITLE
non-ASCII db for normalization

### ISSUE THREAD

**Issue by pierremarchal** [nlplab/brat#1179]
I built a db file for normalization -- encoding is UTF-8 -- which looks like this : 
`6204	name:Name:Oncogène jun	name:Name:jun proto-oncogene	name:Name:AP-1	name:Name:JUN	name:Name:JUN gene	name:Name:c-Jun`
That is, it contains some non-ASCII characters (e.g. è).

I compiled the file in Simstring format using the command: 
`python tools/norm_db_init.py /home/me/gene.db`

And get the following message: 
`Done, imported 39263 entries (162772 strings), skipped 0 duplicate keys, skipped 0 invalid lines`

Now, I can use the normalization functionnality as long as the search terms do not contain any non-ASCII character. For instance I can search "PIK3CA" but not "gène".
Checking my apache log I get:
```
Traceback (most recent call last):
  File "/var/www/html/brat/server/src/server.py", line 322, in serve
    return _safe_serve(params, client_ip, client_hostname, cookie_data)
  File "/var/www/html/brat/server/src/server.py", line 197, in _safe_serve
    json_dic = dispatch(http_args, client_ip, client_hostname)
  File "/var/www/html/brat/server/src/dispatch.py", line 308, in dispatch
    json_dic = action_function(*action_args)
  File "/var/www/html/brat/server/src/norm.py", line 429, in norm_search
    return _norm_search_impl(database, name, collection, exactmatch)
  File "/var/www/html/brat/server/src/norm.py", line 364, in _norm_search_impl
    0, exactmatch)
  File "/var/www/html/brat/server/src/norm.py", line 296, in _norm_search_name_attr
    threshold, True)
  File "/var/www/html/brat/server/src/simstringdb.py", line 236, in ssdb_supstring_lookup
    if s in r:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)  
```

Any idea how I could fix this?
Thanx.

**Comment by pierremarchal** [comment]
I had a similar problem with `tools/norm_db_lookup.py` which I could fix thanx to the `unicode` function:
_tools/norm_db_lookup.py:131_ 
`l = unicode(l,'utf-8') `

I hope it will help me fix my initial problem.

**Comment by pierremarchal** [comment]
I think I got a solution (thanx to [this](http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) SO post). I had to edit `server/src/simstringdb.py`: 
```
#!/usr/bin/env python
# encoding=utf8

import glob
import os
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
