### ISSUE TITLE
Rendering terminated due to: DOMException: Failed to execute 'getStartPositionOfChar' on 'SVGTextContentElement': The charnum provided (0) is greater than or equal to the maximum bound (0).

### ISSUE THREAD

**Issue by loretoparisi** [nlplab/brat#1220]
I'm getting this error, when the `<div/>` container where the svg is placed loses focus like in a tabbed page. Often this happens even when the SVG container belongs to the main container.

Stacktrace:

```
Rendering terminated due to: DOMException: Failed to execute 'getStartPositionOfChar' on 'SVGTextContentElement': The charnum provided (0) is greater than or equal to the maximum bound (0).
    at https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1169:35
    at Fragment.<anonymous> (https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1123:15)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:2815)
    at SVGTextElement.<anonymous> (https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1122:15)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:2815)
    at r.fn.init.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:1003)
    at getTextMeasurements (https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1117:42)
    at getTextAndSpanTextMeasurements (https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1149:25)
    at renderDataReal (https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:1318:21)
    at https://storage.googleapis.com/corenlp/js/brat/client/src/visualizer.js:2698:17
```

This seems not be an error of the rendered data itself, since the input json data are formally valid, and did not change their values during the tab transition.

**Comment by loretoparisi** [comment]
**NOTE**
Then main problem is that there is no way to `catch` this error at least I've not found one like 

```javascript
window.onerror = function (errorMsg, url, lineNumber, column, errorObj) {
                console.log('Error: ' + errorMsg + ' Script: ' + url + ' Line: ' + lineNumber
                + ' Column: ' + column + ' StackTrace: ' +  errorObj);
            };
```

will not trap not those `DOMException` errors.

**Comment by loretoparisi** [comment]
**[UPDATE]**
After looking at the code I can see that the error is already catched here

(visualizer.js:2694)
```
dispatcher.post('startedRendering', [coll, doc, args]);
          dispatcher.post('spin');
          setTimeout(function() {
              try {
                renderDataReal(sourceData);
              } catch (e) {
                // We are sure not to be drawing anymore, reset the state
                drawing = false;
                // TODO: Hook printout into dispatch elsewhere?
                console.warn('Rendering terminated due to:', e);
                dispatcher.post('renderError: Fatal', [sourceData, e]);
              }
              dispatcher.post('unspin');
          }, 0);
```

Any way to attach to this error, in order to try to redraw?
