### ISSUE TITLE
filelock is required

### ISSUE THREAD

**Issue by goFrendiAsgard** [nlplab/brat#1303]
I try to run brat by performing:
```
./install.sh && python standalone.py
```
The server is running as expected, and I can access the homepage. However, I see this error on terminal:
```
[guldan@draenor brat]$ python standalone.py
Serving brat at http://0.0.0.0:8001
Traceback (most recent call last):
  File "server/src/server.py", line 338, in serve
    return _safe_serve(params, client_ip, client_hostname, cookie_data)
  File "server/src/server.py", line 175, in _safe_serve
    from dispatch import dispatch
  File "server/src/dispatch.py", line 18, in <module>
    from annlog import log_annotation
  File "server/src/annlog.py", line 19, in <module>
    from projectconfig import options_get_annlogfile
  File "server/src/projectconfig.py", line 20, in <module>
    from annotation import open_textfile
  File "server/src/annotation.py", line 16, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
```

The problem is then solved after I perform `pip install filelock --user`

I think it is better to put external module dependencies in `requirement.txt`, and either perform `pip install requirement.txt` in installation script or put the instruction in documentation.

Great job BTW :)

**Comment by jeanphilippegoldman** [comment]
config does not come with python installation and is also required so I would add rather this:
pip install config filelock
