### ISSUE TITLE
Cannot run Brat on Windows

### ISSUE THREAD

**Issue by arikadodani** [nlplab/brat#1306]
Hello,

After installing BRAT I ran into the following exception

$ py -2 standalone.py                                                                                                                                             Warning: could not determine user. Note that the brat standalone                 server is experimental and should not be run as administrator.                                                                                                    Serving brat at http://127.0.0.1:8001                                            Traceback (most recent call last):                                                 File "C:\Python27\lib\SocketServer.py", line 284, in _handle_request_noblock       self.process_request(request, client_address)                                  File "C:\Python27\lib\SocketServer.py", line 545, in process_request               pid = os.fork()
--

Attached are the screenshots for your reference:

![image](https://user-images.githubusercontent.com/38332945/51664748-6aeff680-1fba-11e9-97b3-13b04fa4bd21.png)

![image](https://user-images.githubusercontent.com/38332945/51664693-4a27a100-1fba-11e9-8006-09e3c63d47f0.png)

**Comment by jeanphilippegoldman** [comment]
unless you specifically chose branch python2 on this repo, master branch seems to be meant for python3.
it may solve your issue
