### ISSUE TITLE
Need help for deBug to anntoconll.py

### ISSUE THREAD

**Issue by timetrave1** [nlplab/brat#1384]
When I use this program [anntoconll.py]
There is a bug for me and I can't fix it by myself
Bug:
    Traceback (most recent call last):
  File "anntoconll.py", line 328, in <module>
    sys.exit(main(sys.argv))
  File "anntoconll.py", line 324, in main
    process_files(options.text)
  File "anntoconll.py", line 223, in process_files
    lines = process(f)
  File "anntoconll.py", line 208, in process
    return text_to_conll(f)
  File "anntoconll.py", line 157, in text_to_conll
    return StringIO('\n'.join(('\t'.join(l) for l in lines)))
TypeError: initial_value must be unicode or None, not str

Thanks!

**Comment by Heduang** [comment]
你好。我已经收到您的邮件。

**Comment by kakuibeyond** [comment]
I've met the same problem, so how did you solve it? thanks.
