### ISSUE TITLE
ImportError: cannot import name 'WORK_DIR'

### ISSUE THREAD

**Issue by jaioneB** [nlplab/brat#1397]
While running standalone.py, I get this error. Any ideas?

Traceback (most recent call last):
  File "server/src/annotation.py", line 135, in <module>
    from common import WORK_DIR
ImportError: cannot import name 'WORK_DIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server/src/server.py", line 338, in serve
    return _safe_serve(params, client_ip, client_hostname, cookie_data)
  File "server/src/server.py", line 175, in _safe_serve
    from dispatch import dispatch
  File "server/src/dispatch.py", line 18, in <module>
    from annlog import log_annotation
  File "server/src/annlog.py", line 19, in <module>
    from projectconfig import options_get_annlogfile
  File "server/src/projectconfig.py", line 20, in <module>
    from annotation import open_textfile
  File "server/src/annotation.py", line 141, in <module>
    except (ModuleNotFoundError, ImportError):
NameError: name 'ModuleNotFoundError' is not defined

**Comment by anthobio23** [comment]
hello, how did you get the brad tool? I try to download from the page and it does not work. did you use it from github?

**Comment by jaioneB** [comment]
Yes, I downloaded the github version. Turns out this recent version works with python3, which was causing me the error. I used python 3.8.10 and it's finally working :)

**Comment by ghost** [comment]
Good, looks close-able to me.
