### ISSUE TITLE
Server crash on opening collection

### ISSUE THREAD

**Issue by TomokoOhta** [nlplab/brat#845]
Current brat master crashes systematically on opening a particular collection (glucose metabolism) with

```
Traceback (most recent call last): 
File "/home/okap/public_html/brat/server/src/server.py", line 313, in serve 
return _safe_serve(params, client_ip, client_hostname, cookie_data) 
File "/home/okap/public_html/brat/server/src/server.py", line 195, in _safe_serve 
json_dic = dispatch(http_args, client_ip, client_hostname) 
File "/home/okap/public_html/brat/server/src/dispatch.py", line 269, in dispatch 
json_dic = action_function(*action_args) 
File "/home/okap/public_html/brat/server/src/document.py", line 488, in get_directory_information 
doclist = [doclist[i] + doc_stats[i] for i in range(len(doclist))] 
IndexError: list index out of range 
```

**Comment by demongolem** [comment]
Any movement on this?  In the 1.3v release the line of error is 518.

**Comment by rain1024** [comment]
Any movement on this? I'm facing with this issue but I can't find anything to get me out

**Comment by doctor-entropy** [comment]
First solution: Just 'cd' into the folder giving you the error and delete the '.stats_cache' file (rm .stats_cache). It should fix it.

Second: To ensure this problem does not occur in the future, go to brat/server/src and edit line 87 of stats.py file, Set generate=True
