### ISSUE TITLE
Standalone server crashes on windows, no os.fork()

### ISSUE THREAD

**Issue by spyysalo** [nlplab/brat#993]
Report from user: standalone server crashes on windows with

```
Exception happened during processing of request from ('127.0.0.1', 63290)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 545, in process_request
    pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'
```

`os.fork()` is apparently not available on windows.

One alternative for `fork`: http://docs.python.org/2/library/multiprocessing.html

**Comment by eromoe** [comment]
Get this error in newest version

```
E:\Project\allproject_git\brat>python standalone.py

Warning: could not determine user. Note that the brat standalone
server is experimental and should not be run as administrator.

Serving brat at http://0.0.0.0:8001
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 5862)
Traceback (most recent call last):
  File "D:\Python27\lib\SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "D:\Python27\lib\SocketServer.py", line 559, in process_request
    pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 5863)
Traceback (most recent call last):
  File "D:\Python27\lib\SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "D:\Python27\lib\SocketServer.py", line 559, in process_request
    pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'
----------------------------------------
```
